# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-gtk/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-gtk

MAINTAINER=	luca.pizzamiglio@gmail.com
COMMENT=	Gtk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_SUB+=	TIMID_LIBDIR=${TIMID_LIBDIR}

.include "${MASTERDIR}/Makefile"
