# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-xskin/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-xskin

MAINTAINER=	luca.pizzamiglio@gmail.com
COMMENT=	X11AMP skin interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
