# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-tcltk/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-tcltk

MAINTAINER=	luca.pizzamiglio@gmail.com
COMMENT=	Tcl/Tk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
