# Created by: Yoichi Asai <yatt@luna2.org>
# $FreeBSD: audio/timidity++-xaw/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-xaw

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Xaw interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++
NO_STAGE=	yes

.include "${MASTERDIR}/Makefile"
