# Created by: Yoichi Asai <yatt@luna2.org>
# $FreeBSD: audio/timidity++-xaw/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-xaw

MAINTAINER=	luca.pizzamiglio@gmail.com
COMMENT=	Xaw interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
