# Created by: Yoichi Asai <yatt@luna2.org>
# $FreeBSD: audio/timidity++-emacs/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-emacs

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Emacs interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++
PLIST_SUB+=	ELISPDIR=${ELISPDIR}
#PLIST_FILES=	${TIMID_LIBDIR}/if_emacs.so ${ELISPDIR}/timidity.el

.include "${MASTERDIR}/Makefile"
