# Created by: Yoichi Asai <yatt@luna2.org>
# $FreeBSD: audio/timidity++-emacs/Makefile 327706 2013-09-20 14:36:35Z bapt $

PKGNAMESUFFIX=	-emacs

MAINTAINER=	luca.pizzamiglio@gmail.com
COMMENT=	Emacs interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++
PLIST_SUB+=	ELISPDIR=${ELISPDIR}

.include "${MASTERDIR}/Makefile"
